TOWERS = {
    'dota_goodguys_tower1_top': {'x': 517, 'y': 3860 - 2126},
    'dota_goodguys_tower2_top': {'x': 531, 'y': 3860 - 1449},
    'dota_goodguys_tower3_top': {'x': 295, 'y': 3860 - 2756},
    'dota_goodguys_tower4_top': {'x': 634, 'y': 3860 - 3154},
    'dota_goodguys_tower4_bot': {'x': 709, 'y': 3860 - 3220},
    'dota_goodguys_tower1_mid': {'x': 1689, 'y': 3860 - 2262},
    'dota_goodguys_tower2_mid': {'x': 1183, 'y': 3860 - 2618},
    'dota_goodguys_tower3_mid': {'x': 906, 'y': 3860 - 2951},
#    'dota_goodguys_tower1_bot': {'x': 4077, 'y': 3860 - 4442, 'worldY' : 48}, # bug
#    'dota_goodguys_tower2_bot': {'x': 2369, 'y': 3860 - 4439, 'worldY' : 48}, # bug
#    'dota_goodguys_tower3_bot': {'x': 487, 'y': 3860 - 3576},
    'dota_badguys_tower1_top': {'x': 874, 'y': 3860 - 396},
    'dota_badguys_tower2_top': {'x': 2073, 'y': 3860 - 394},
    'dota_badguys_tower3_top': {'x': 2956, 'y': 3860 - 453},
    'dota_badguys_tower1_mid': {'x': 2327, 'y': 3860 - 1836},
    'dota_badguys_tower2_mid': {'x': 2702, 'y': 3860 - 1375},
    'dota_badguys_tower3_mid': {'x': 3141, 'y': 3860 - 975},
    'dota_badguys_tower1_bot': {'x': 3645, 'y': 3860 - 2338},
    'dota_badguys_tower2_bot': {'x': 3663, 'y': 3860 - 1820},
    'dota_badguys_tower3_bot': {'x': 3660, 'y': 3860 - 1160},
}

COLORS = {
    0 : "#0000FF",
    1 : "#00E1FF",
    2 : "#AE00FF",
    3 : "#FFF700",
    4 : "#FF8800",

    5 : "#FF80DF",
    6 : "#CCC470",
    7 : "#589AA3",
    8 : "#4D8742",
    9 : "#573B1E",

}

HEROES = {
   1:{
      'name':'Antimage',
      'entity_name':'npc_dota_hero_antimage'
   },
   2:{
      'name':'Axe',
      'entity_name':'npc_dota_hero_axe'
   },
   3:{
      'name':'Bane',
      'entity_name':'npc_dota_hero_bane'
   },
   4:{
      'name':'Bloodseeker',
      'entity_name':'npc_dota_hero_bloodseeker'
   },
   5:{
      'name':'Maiden',
      'entity_name':'npc_dota_hero_crystal_maiden'
   },
   6:{
      'name':'Ranger',
      'entity_name':'npc_dota_hero_drow_ranger'
   },
   7:{
      'name':'Earthshaker',
      'entity_name':'npc_dota_hero_earthshaker'
   },
   8:{
      'name':'Juggernaut',
      'entity_name':'npc_dota_hero_juggernaut'
   },
   9:{
      'name':'Mirana',
      'entity_name':'npc_dota_hero_mirana'
   },
   10:{
      'name':'Morphling',
      'entity_name':'npc_dota_hero_morphling'
   },
   11:{
      'name':'Nevermore',
      'entity_name':'npc_dota_hero_nevermore'
   },
   12:{
      'name':'Lancer',
      'entity_name':'npc_dota_hero_phantom_lancer'
   },
   13:{
      'name':'Puck',
      'entity_name':'npc_dota_hero_puck'
   },
   14:{
      'name':'Pudge',
      'entity_name':'npc_dota_hero_pudge'
   },
   15:{
      'name':'Razor',
      'entity_name':'npc_dota_hero_razor'
   },
   16:{
      'name':'King',
      'entity_name':'npc_dota_hero_sand_king'
   },
   17:{
      'name':'Spirit',
      'entity_name':'npc_dota_hero_storm_spirit'
   },
   18:{
      'name':'Sven',
      'entity_name':'npc_dota_hero_sven'
   },
   19:{
      'name':'Tiny',
      'entity_name':'npc_dota_hero_tiny'
   },
   20:{
      'name':'Vengefulspirit',
      'entity_name':'npc_dota_hero_vengefulspirit'
   },
   21:{
      'name':'Windrunner',
      'entity_name':'npc_dota_hero_windrunner'
   },
   22:{
      'name':'Zuus',
      'entity_name':'npc_dota_hero_zuus'
   },
   23:{
      'name':'Kunkka',
      'entity_name':'npc_dota_hero_kunkka'
   },
   25:{
      'name':'Lina',
      'entity_name':'npc_dota_hero_lina'
   },
   26:{
      'name':'Lion',
      'entity_name':'npc_dota_hero_lion'
   },
   27:{
      'name':'Shaman',
      'entity_name':'npc_dota_hero_shadow_shaman'
   },
   28:{
      'name':'Slardar',
      'entity_name':'npc_dota_hero_slardar'
   },
   29:{
      'name':'Tidehunter',
      'entity_name':'npc_dota_hero_tidehunter'
   },
   30:{
      'name':'Doctor',
      'entity_name':'npc_dota_hero_witch_doctor'
   },
   31:{
      'name':'Lich',
      'entity_name':'npc_dota_hero_lich'
   },
   32:{
      'name':'Riki',
      'entity_name':'npc_dota_hero_riki'
   },
   33:{
      'name':'Enigma',
      'entity_name':'npc_dota_hero_enigma'
   },
   34:{
      'name':'Tinker',
      'entity_name':'npc_dota_hero_tinker'
   },
   35:{
      'name':'Sniper',
      'entity_name':'npc_dota_hero_sniper'
   },
   36:{
      'name':'Necrolyte',
      'entity_name':'npc_dota_hero_necrolyte'
   },
   37:{
      'name':'Warlock',
      'entity_name':'npc_dota_hero_warlock'
   },
   38:{
      'name':'Beastmaster',
      'entity_name':'npc_dota_hero_beastmaster'
   },
   39:{
      'name':'Queenofpain',
      'entity_name':'npc_dota_hero_queenofpain'
   },
   40:{
      'name':'Venomancer',
      'entity_name':'npc_dota_hero_venomancer'
   },
   41:{
      'name':'Void',
      'entity_name':'npc_dota_hero_faceless_void'
   },
   42:{
      'name':'King',
      'entity_name':'npc_dota_hero_skeleton_king'
   },
   43:{
      'name':'Prophet',
      'entity_name':'npc_dota_hero_death_prophet'
   },
   44:{
      'name':'Assassin',
      'entity_name':'npc_dota_hero_phantom_assassin'
   },
   45:{
      'name':'Pugna',
      'entity_name':'npc_dota_hero_pugna'
   },
   46:{
      'name':'Assassin',
      'entity_name':'npc_dota_hero_templar_assassin'
   },
   47:{
      'name':'Viper',
      'entity_name':'npc_dota_hero_viper'
   },
   48:{
      'name':'Luna',
      'entity_name':'npc_dota_hero_luna'
   },
   49:{
      'name':'Knight',
      'entity_name':'npc_dota_hero_dragon_knight'
   },
   50:{
      'name':'Dazzle',
      'entity_name':'npc_dota_hero_dazzle'
   },
   51:{
      'name':'Rattletrap',
      'entity_name':'npc_dota_hero_rattletrap'
   },
   52:{
      'name':'Leshrac',
      'entity_name':'npc_dota_hero_leshrac'
   },
   53:{
      'name':'Furion',
      'entity_name':'npc_dota_hero_furion'
   },
   54:{
      'name':'Stealer',
      'entity_name':'npc_dota_hero_life_stealer'
   },
   55:{
      'name':'Seer',
      'entity_name':'npc_dota_hero_dark_seer'
   },
   56:{
      'name':'Clinkz',
      'entity_name':'npc_dota_hero_clinkz'
   },
   57:{
      'name':'Omniknight',
      'entity_name':'npc_dota_hero_omniknight'
   },
   58:{
      'name':'Enchantress',
      'entity_name':'npc_dota_hero_enchantress'
   },
   59:{
      'name':'Huskar',
      'entity_name':'npc_dota_hero_huskar'
   },
   60:{
      'name':'Stalker',
      'entity_name':'npc_dota_hero_night_stalker'
   },
   61:{
      'name':'Broodmother',
      'entity_name':'npc_dota_hero_broodmother'
   },
   62:{
      'name':'Hunter',
      'entity_name':'npc_dota_hero_bounty_hunter'
   },
   63:{
      'name':'Weaver',
      'entity_name':'npc_dota_hero_weaver'
   },
   64:{
      'name':'Jakiro',
      'entity_name':'npc_dota_hero_jakiro'
   },
   65:{
      'name':'Batrider',
      'entity_name':'npc_dota_hero_batrider'
   },
   66:{
      'name':'Chen',
      'entity_name':'npc_dota_hero_chen'
   },
   67:{
      'name':'Spectre',
      'entity_name':'npc_dota_hero_spectre'
   },
   68:{
      'name':'Apparition',
      'entity_name':'npc_dota_hero_ancient_apparition'
   },
   69:{
      'name':'Bringer',
      'entity_name':'npc_dota_hero_doom_bringer'
   },
   70:{
      'name':'Ursa',
      'entity_name':'npc_dota_hero_ursa'
   },
   71:{
      'name':'Breaker',
      'entity_name':'npc_dota_hero_spirit_breaker'
   },
   72:{
      'name':'Gyrocopter',
      'entity_name':'npc_dota_hero_gyrocopter'
   },
   73:{
      'name':'Alchemist',
      'entity_name':'npc_dota_hero_alchemist'
   },
   74:{
      'name':'Invoker',
      'entity_name':'npc_dota_hero_invoker'
   },
   75:{
      'name':'Silencer',
      'entity_name':'npc_dota_hero_silencer'
   },
   76:{
      'name':'Destroyer',
      'entity_name':'npc_dota_hero_obsidian_destroyer'
   },
   77:{
      'name':'Lycan',
      'entity_name':'npc_dota_hero_lycan'
   },
   78:{
      'name':'Brewmaster',
      'entity_name':'npc_dota_hero_brewmaster'
   },
   79:{
      'name':'Demon',
      'entity_name':'npc_dota_hero_shadow_demon'
   },
   80:{
      'name':'Druid',
      'entity_name':'npc_dota_hero_lone_druid'
   },
   81:{
      'name':'Knight',
      'entity_name':'npc_dota_hero_chaos_knight'
   },
   82:{
      'name':'Meepo',
      'entity_name':'npc_dota_hero_meepo'
   },
   83:{
      'name':'Treant',
      'entity_name':'npc_dota_hero_treant'
   },
   84:{
      'name':'Magi',
      'entity_name':'npc_dota_hero_ogre_magi'
   },
   85:{
      'name':'Undying',
      'entity_name':'npc_dota_hero_undying'
   },
   86:{
      'name':'Rubick',
      'entity_name':'npc_dota_hero_rubick'
   },
   87:{
      'name':'Disruptor',
      'entity_name':'npc_dota_hero_disruptor'
   },
   88:{
      'name':'Assassin',
      'entity_name':'npc_dota_hero_nyx_assassin'
   },
   89:{
      'name':'Siren',
      'entity_name':'npc_dota_hero_naga_siren'
   },
   90:{
      'name':'Light',
      'entity_name':'npc_dota_hero_keeper_of_the_light'
   },
   91:{
      'name':'Wisp',
      'entity_name':'npc_dota_hero_wisp'
   },
   92:{
      'name':'Visage',
      'entity_name':'npc_dota_hero_visage'
   },
   93:{
      'name':'Slark',
      'entity_name':'npc_dota_hero_slark'
   },
   94:{
      'name':'Medusa',
      'entity_name':'npc_dota_hero_medusa'
   },
   95:{
      'name':'Warlord',
      'entity_name':'npc_dota_hero_troll_warlord'
   },
   96:{
      'name':'Centaur',
      'entity_name':'npc_dota_hero_centaur'
   },
   97:{
      'name':'Magnataur',
      'entity_name':'npc_dota_hero_magnataur'
   },
   98:{
      'name':'Shredder',
      'entity_name':'npc_dota_hero_shredder'
   },
   99:{
      'name':'Bristleback',
      'entity_name':'npc_dota_hero_bristleback'
   },
   100:{
      'name':'Tusk',
      'entity_name':'npc_dota_hero_tusk'
   },
   101:{
      'name':'Mage',
      'entity_name':'npc_dota_hero_skywrath_mage'
   },
   102:{
      'name':'Abaddon',
      'entity_name':'npc_dota_hero_abaddon'
   },
   103:{
      'name':'Titan',
      'entity_name':'npc_dota_hero_elder_titan'
   },
   104:{
      'name':'Commander',
      'entity_name':'npc_dota_hero_legion_commander'
   },
   105:{
      'name':'Techies',
      'entity_name':'npc_dota_hero_techies'
   },
   106:{
      'name':'Spirit',
      'entity_name':'npc_dota_hero_ember_spirit'
   },
   107:{
      'name':'Spirit',
      'entity_name':'npc_dota_hero_earth_spirit'
   },
   109:{
      'name':'Terrorblade',
      'entity_name':'npc_dota_hero_terrorblade'
   },
   110:{
      'name':'Phoenix',
      'entity_name':'npc_dota_hero_phoenix'
   }
}